---
title: "Diagnostics"
author: "Anastasia Bernat"
output: html_document
---

```{r setup, include=FALSE}
rm(list=ls())
library(stringr)

dir = "/Users/anastasiabernat/Desktop/git_repositories/flight-mill/parallel_processing/"
setwd(dir)
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
inpath = paste0(dir, "diagnostics/")
```

## Summary 

```{r}
sums = read.csv(paste0(inpath,"diagnostics_summary.csv"))
```

```{r fig.width = 5, fig.height=4}
#num_noise_files = 21 # not all of these are large changes but represent noise_files
paste("Total small changes across sets: ", sum(sums$small_changes) / 3)
paste("Total large changes across sets: ", sum(sums$large_changes) / 3 ) # - num_noise_files) 

par(mfrow=c(2,2))

plot(sums$total, sums$small_changes, main="Positive", 
     xlab="Total Trials", ylab="Num of Small Changes")
m = lm(small_changes ~ total, data=sums)
abline(m, col="grey")
summary(m)

plot(sums$total, sums$large_changes, main="Positive Relationship", 
     xlab="Total Trials", ylab="Num of Large Changes")
m = lm(large_changes ~ total, data=sums)
abline(m, col="grey")
summary(m)

plot(sums$small_changes, sums$large_changes, main="Positive Relationship", 
     xlab="Num of Small Changes", ylab="Num of Large Changes")
m = lm(large_changes ~ small_changes, data=sums) # not significant
abline(m, col="grey")
summary(m)
```

## Chamber

```{r}
# for when I want to do the Kruskal-Wallis chamber analyses
# ID
# substring(ID, regexpr("_", ID) + 0 )
# id = unlist(strsplit(ID, ","))
# chamberA = str_extract(string = id, pattern = "A[0-9]+")
# chamberB = str_extract(string = id, pattern = "B[0-9]+")
# chambers = c(unique(chamberA[grepl("A", chamberA)]), 
#              unique(chamberB[grepl("B", chamberB)]))
# chambers
# for (ID in sums$large_cIDs) {
#   ID[1][1]
#   test = ID[ID != "None"]
#   print(test)
# }
# gsub("B1")
```


## Sets 

```{r}
data = read.csv(paste0(inpath,"diagnostics_combos.csv")) # get the number from the set
data[order(data$set),]
```

```{r}
par(mfrow=c(2,3))
for (i in seq(0,nrow(data) - 3, 3)) {
  matrix = data[(i+1):(i+3),c(2, 4:length(data))]
  d = t(matrix)
  filename = d[1,][1]
  plot(d[-1,1], main="Number Troughs", sub=filename, 
       xlab="Combo", ylab="Number of Troughs", col="black")
  plot(d[-1,2], main="Speed", xlab="Combo", ylab="Speed", col="blue")
  plot(d[-1,3], main="Distance", xlab="Combo", ylab="Distance", col="red")
}

```

## Clusters of Three

```{r}
data1 = read.csv("diagnostics/by_set/diagnostics_combos-set001.csv")
data2 = read.csv("diagnostics/by_set/diagnostics_combos-set002.csv")
data3 = read.csv("diagnostics/by_set/diagnostics_combos-set003.csv")
data = rbind(data1, data2, data3)
data
```

```{r}
par(mfrow=c(2,3))
for (i in seq(0,nrow(data) - 3, 3)) {
  matrix = data[(i+1):(i+3),c(2, 4:length(data))]
  d = t(matrix)
  filename = d[1,][1]
  plot(d[-1,1], main="Number Troughs", sub=filename, 
       xlab="Combo", ylab="Number of Troughs", col="black")
  plot(d[-1,2], main="Speed", xlab="Combo", ylab="Speed", col="blue")
  plot(d[-1,3], main="Distance", xlab="Combo", ylab="Distance", col="red")
}
```

## Single Plot

```{r}
matrix = data[3:6,4:length(data)]
d = t(matrix)

plot(d[,1], main="Number Troughs", xlab="Combo", ylab="Number of Troughs")
plot(d[,3], main="Speed", xlab="Combo", ylab="Speed")
plot(d[,2], main="Distance", xlab="Combo", ylab="Distance")
```




